# Generated by Django 3.2.9 on 2024-12-04 17:45

import bson.objectid
from django.db import migrations
import rbac_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_app', '0002_auto_20241204_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='_id',
            field=rbac_app.models.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='_id',
            field=rbac_app.models.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='role',
            name='_id',
            field=rbac_app.models.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='_id',
            field=rbac_app.models.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
    ]
